### DISCUSSION TITLE
[subgraph-package branch] Help regarding The Graph Explorer: Query returning null

### DISCUSSION THREAD

**Discussion by RafaDSan** [scaffold-eth/scaffold-eth-2#545] [Q&A]
### Basic explanation of the problem

I'm working on a local subgraph for tracking events on an Ethereum smart contract. I aim to query specific entities, but I'm encountering a `null` result when attempting to do so. I am stuck on this for days and am just a noob yet, so I would greatly appreciate your help.

#### The result:

`{
  "data": {
    "taskCreated": null
  }
}`

### Steps to reproduce the problem

I am following the tutorial https://mirror.xyz/cryptomastery.eth/uGHEHnskoVwX-mWjAiidXfGt6QowCoKl_yX4okwZc0E which basically teaches how to plug and play this repo, which worked just fine. Then I adapted the code to use my smart contracts and I configured the subgraphs files as follows:

#### My query:

```
query MyQuery {
  taskCreated(id: "0") {
    creator
    assignee
    reward
    endDate
  }
}
```

#### schema.graphql
```
type TaskCreated @entity {
  id: ID!
  taskId: BigInt! # uint256
  creator: Bytes! # address
  assignee: Bytes! # address
  reward: BigInt! # uint256
  endDate: BigInt! # uint256
}
```

#### subgraph.yaml

```
specVersion: 0.0.5
schema:
  file: ./schema.graphql
dataSources:
  - kind: ethereum
    name: TasksManager
    network: localhost
    source:
      address: "0xdc64a140aa3e981100a9beca4e685f962f0cf6c9"
      abi: TasksManager
      startBlock: 3
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - TaskCreated
      abis:
        - name: TasksManager
          file: ./abis/TasksManager.json
      eventHandlers:
        - event: TaskCreated(indexed uint256,indexed address,indexed address,uint256,uint256)
          handler: handleTaskCreated
      file: ./src/tasks-manager.ts

```

#### My event created:

```
event TaskCreated(
    uint256 indexed taskId,
    address indexed creator,
    address indexed assignee,
    uint256 reward,
    uint256 endDate
);


```

#### My function to test emit it:

```
function teste() public {
    emit TaskCreated(0, msg.sender, msg.sender, 18, 20401);
    emit TaskCreated(1, msg.sender, msg.sender, 20, 20561);
    emit TaskCreated(2, msg.sender, msg.sender, 15, 35601);
}
```

#### My deploy script: 

```
const Factory = await ethers.getContractFactory("TasksManager", deployer);
 
const contract = new ethers.Contract(
   taskFactory.address,
   TasksManagerAbi.abi,
   deployer
 );
 const tx = await contract.teste();
 console.log("Esta é a transação do createTask:", tx.hash);
}

```

#### Hardhat log:

 Contract call:       <UnrecognizedContract>
  Transaction:         0x9ea259f119cc8008d5cdae60e40f64c4c001467600f3e6d2c84e017c5b63790a
  From:                0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266
  To:                  0xcf7ed3acca5a467e9e704c703e8d87f634fb0fc9
  Value:               0 ETH
  Gas used:            28797 of 28797
  Block #6:            0x9450f9a4d2bd50799d3dadaf8ecbe32a74be5e6c426c1ae09235d71f1a8e7775

eth_chainId
eth_getTransactionByHash
eth_getBlockByNumber
eth_getBlockByHash
eth_getTransactionReceipt
eth_getBlockByHash
eth_getTransactionReceipt
eth_getBlockByNumber (75)
eth_chainId
eth_getBlockByNumber (1466)

---

Any ideas on what could be causing this result?
